import * as cheerio from 'cheerio';
import { changeReport, getProduct, listJobs, listProducts, listProfiles, queueOverview } from './db.js';
import { destinationOverview, listDestinationProducts } from './maintenance.js';
import { basalamChats, basalamOrders } from './automation.js';
import { basalamCategories } from './product-ai.js';
import { testSelector } from './scraper.js';
import { safeFetch } from './network.js';
import { loadConnections } from './connections.js';
import { sourceDiagnostics } from './source-network.js';
import { validateImage } from './media.js';

export type ToolCallTrace={name:string;arguments:Record<string,unknown>;result:unknown;ok:boolean;durationMs:number};
type Tool={description:string;properties:Record<string,unknown>;required?:string[];run:(args:any)=>Promise<unknown>};
const limit=(value:unknown,max=50)=>Math.max(1,Math.min(max,Number(value)||10));
const text=(value:unknown,max=500)=>String(value||'').slice(0,max);
const target=(value:unknown):'woo'|'basalam'=>value==='basalam'?'basalam':'woo';

const registry:Record<string,Tool>={
  list_profiles:{description:'فهرست پروفایل‌های استخراج و وضعیت اجرای آن‌ها',properties:{},run:async()=>({profiles:(await listProfiles()).map(p=>({id:p.id,name:p.name,url:p.url,enabled:p.enabled,lastRunAt:p.lastRunAt,syncWoo:p.syncWoo,syncBasalam:p.syncBasalam}))})},
  search_products:{description:'جستجوی محصولات محلی با شناسه پروفایل و عبارت عنوان',properties:{profileId:{type:'string'},query:{type:'string'},limit:{type:'integer',minimum:1,maximum:50}},required:['profileId'],run:async a=>listProducts(text(a.profileId,100),limit(a.limit),0,text(a.query,200))},
  get_product:{description:'دریافت مشخصات کامل یک محصول محلی',properties:{profileId:{type:'string'},sourceKey:{type:'string'}},required:['profileId','sourceKey'],run:async a=>({product:await getProduct(text(a.profileId,100),text(a.sourceKey,300))})},
  queue_status:{description:'مشاهده وضعیت صف‌ها و آخرین کارها؛ فقط خواندنی',properties:{limit:{type:'integer',minimum:1,maximum:50}},run:async a=>({overview:await queueOverview(),jobs:await listJobs(limit(a.limit))})},
  recent_changes:{description:'گزارش تغییرات اخیر قیمت، موجودی و محصولات',properties:{hours:{type:'integer',minimum:1,maximum:8760},profileId:{type:'string'},limit:{type:'integer',minimum:1,maximum:100}},run:async a=>changeReport({hours:limit(a.hours,8760),profileId:text(a.profileId,100)||undefined,limit:limit(a.limit,100)})},
  destination_overview:{description:'خلاصه محصولات ووکامرس یا باسلام و وضعیت تصویر/SKU',properties:{target:{type:'string',enum:['woo','basalam']}},required:['target'],run:async a=>destinationOverview(target(a.target))},
  search_destination_products:{description:'جستجوی خواندنی محصولات مقصد ووکامرس یا باسلام',properties:{target:{type:'string',enum:['woo','basalam']},query:{type:'string'},limit:{type:'integer',minimum:1,maximum:50}},required:['target'],run:async a=>{const q=text(a.query,200).toLowerCase(),rows=await listDestinationProducts(target(a.target));return{items:rows.filter(x=>!q||x.name.toLowerCase().includes(q)||String(x.sku||'').toLowerCase().includes(q)).slice(0,limit(a.limit))}}},
  list_basalam_categories:{description:'جستجو در دسته‌بندی‌های باسلام برای پیشنهاد دسته واقعی',properties:{query:{type:'string'},limit:{type:'integer',minimum:1,maximum:100}},run:async a=>{const q=text(a.query,200).toLowerCase(),rows=await basalamCategories();return{items:rows.filter(x=>!q||x.name.toLowerCase().includes(q)).slice(0,limit(a.limit,100))}}},
  list_woo_categories:{description:'جستجو در دسته‌بندی‌های واقعی ووکامرس',properties:{query:{type:'string'},limit:{type:'integer',minimum:1,maximum:100}},run:async a=>{const c=(await loadConnections()).woo;if(!c.url||!c.key||!c.secret)throw Error('اتصال ووکامرس کامل نیست');const auth=`Basic ${Buffer.from(`${c.key}:${c.secret}`).toString('base64')}`,r=await safeFetch(`${c.url}/wp-json/wc/v3/products/categories?per_page=100`,{headers:{authorization:auth,accept:'application/json'}},3_000_000),rows=await r.json() as any[];if(!r.ok)throw Error(`Woo categories HTTP ${r.status}`);const q=text(a.query,200).toLowerCase();return{items:rows.filter(x=>!q||String(x.name||'').toLowerCase().includes(q)).slice(0,limit(a.limit,100))}}},
  validate_image:{description:'بررسی سلامت، نوع محتوا و دسترسی یک تصویر؛ فقط خواندنی',properties:{url:{type:'string'}},required:['url'],run:async a=>validateImage(text(a.url,2000))},
  source_diagnostics:{description:'عیب‌یابی مسیرهای اتصال به یک URL عمومی مبدأ؛ فقط خواندنی',properties:{url:{type:'string'}},required:['url'],run:async a=>sourceDiagnostics(text(a.url,2000))},
  get_basalam_orders:{description:'دریافت آخرین سفارش‌های باسلام؛ فقط خواندنی',properties:{limit:{type:'integer',minimum:1,maximum:30}},run:async a=>({items:await basalamOrders(limit(a.limit,30))})},
  get_basalam_chats:{description:'دریافت فهرست گفتگوهای باسلام؛ فقط خواندنی و بدون ارسال پاسخ',properties:{limit:{type:'integer',minimum:1,maximum:50}},run:async a=>({items:await basalamChats(limit(a.limit,50))})},
  test_selector:{description:'آزمایش یک CSS selector روی صفحه مبدأ؛ فقط خواندنی',properties:{url:{type:'string'},selector:{type:'string'},type:{type:'string',enum:['text','href','src']}},required:['url','selector'],run:async a=>testSelector(text(a.url,2000),text(a.selector,500),text(a.type,20)||'text')},
  web_search:{description:'جستجو در وب عمومی. ممکن است سرویس جستجوی عمومی در بعضی شبکه‌ها محدود باشد.',properties:{query:{type:'string'},limit:{type:'integer',minimum:1,maximum:10}},required:['query'],run:async a=>webSearch(text(a.query,300),limit(a.limit,10))},
  web_fetch:{description:'خواندن متن یک صفحه عمومی وب با محافظت SSRF؛ بدون اجرای JavaScript',properties:{url:{type:'string'}},required:['url'],run:async a=>webFetch(text(a.url,2000))},
  preview_product_update:{description:'ساخت پیش‌نمایش تغییر محصول محلی؛ هیچ تغییری اجرا نمی‌شود',properties:{profileId:{type:'string'},sourceKey:{type:'string'},patch:{type:'object'}},required:['profileId','sourceKey','patch'],run:async a=>({ok:true,dryRun:true,requiresConfirmation:'APPLY',operation:'local_product_update',profileId:text(a.profileId,100),sourceKey:text(a.sourceKey,300),patch:safePatch(a.patch)})},
  preview_destination_update:{description:'ساخت پیش‌نمایش تغییر محصول ووکامرس/باسلام؛ هیچ تغییری اجرا نمی‌شود',properties:{target:{type:'string',enum:['woo','basalam']},id:{type:'integer'},patch:{type:'object'}},required:['target','id','patch'],run:async a=>({ok:true,dryRun:true,requiresConfirmation:'APPLY',operation:'destination_update',target:target(a.target),id:Number(a.id),patch:safePatch(a.patch)})},
  preview_queue_action:{description:'ساخت پیش‌نمایش توقف، تلاش مجدد یا حذف کار صف؛ اجرا نمی‌شود',properties:{jobId:{type:'string'},action:{type:'string',enum:['stop','retry','delete']}},required:['jobId','action'],run:async a=>({ok:true,dryRun:true,requiresConfirmation:'APPLY',operation:'queue_'+text(a.action,20),jobId:text(a.jobId,100)})}
};

export const AI_TOOL_DEFINITIONS=Object.entries(registry).map(([name,t])=>({type:'function',function:{name,description:t.description,parameters:{type:'object',properties:t.properties,required:t.required||[],additionalProperties:false}}}));
export function aiToolNames(){return Object.keys(registry)}
export async function executeAiTool(name:string,args:unknown):Promise<ToolCallTrace>{const tool=registry[name],started=Date.now(),input=args&&typeof args==='object'&&!Array.isArray(args)?args as Record<string,unknown>:{};if(!tool)return{name,arguments:input,result:{error:'ابزار ناشناخته یا غیرمجاز است'},ok:false,durationMs:Date.now()-started};try{return{name,arguments:input,result:await tool.run(input),ok:true,durationMs:Date.now()-started}}catch(error){return{name,arguments:input,result:{error:error instanceof Error?error.message:String(error)},ok:false,durationMs:Date.now()-started}}}
function safePatch(value:any){const out:Record<string,unknown>={};for(const key of ['title','name','price','stock','category','categoryId','status','image','shortDesc','longDesc'])if(value&&Object.prototype.hasOwnProperty.call(value,key))out[key]=typeof value[key]==='string'?text(value[key],2000):value[key];return out}
async function webSearch(query:string,count:number){const url='https://html.duckduckgo.com/html/?q='+encodeURIComponent(query),r=await safeFetch(url,{headers:{'user-agent':'Mozilla/5.0 Scraper4-Render/2','accept':'text/html'}},1_500_000);if(!r.ok)throw Error(`Web search HTTP ${r.status}`);const $=cheerio.load(await r.text()),items:any[]=[];$('.result').each((_,el)=>{if(items.length>=count)return;const link=$(el).find('.result__a').first(),snippet=$(el).find('.result__snippet').first().text().replace(/\s+/g,' ').trim(),href=link.attr('href')||'';if(link.text().trim())items.push({title:link.text().trim(),url:decodeDuckUrl(href),snippet})});return{query,engine:'DuckDuckGo HTML',items}}
async function webFetch(url:string){const r=await safeFetch(url,{headers:{'user-agent':'Mozilla/5.0 Scraper4-Render/2','accept':'text/html,text/plain'}},2_000_000);if(!r.ok)throw Error(`Web fetch HTTP ${r.status}`);const type=r.headers.get('content-type')||'',raw=await r.text();if(!type.includes('html'))return{url:r.url||url,text:raw.slice(0,15000)};const $=cheerio.load(raw);$('script,style,noscript,svg').remove();return{url:r.url||url,title:$('title').text().trim(),text:$('body').text().replace(/\s+/g,' ').trim().slice(0,15000)}}
function decodeDuckUrl(href:string){try{const u=new URL(href,'https://duckduckgo.com');return u.searchParams.get('uddg')||u.href}catch{return href}}
