import { Agent, ProxyAgent, fetch as undiciFetch } from 'undici';
import { assertPublicUrl, privateIp, safeFetch } from './network.js';
import { loadConnections } from './connections.js';
import { getState, setState } from './db.js';
import { looksReasoningModel } from './model-catalog.js';
import { AI_TOOL_DEFINITIONS, executeAiTool, type ToolCallTrace } from './ai-tools.js';

export type Provider={id:string;name:string;baseUrl:string;apiKey:string;models:string[];reasoningModels:string[];toolModels:string[];enabled:boolean;kind?:'openai'|'ollama'|'cloudflare'};
export type AiTestOptions={prompt?:string;categoryTitle?:string;perProvider?:number;delayMs?:number;onlyUntested?:boolean;onlyCandidates?:boolean};
type Network={mode:string;proxyUrl:string;workerUrl:string;dohUrl:string;resolveIp:string};

export async function aiProviders():Promise<Provider[]>{const ai=(await loadConnections()).ai;return ai.providers.length?[...ai.providers].sort((a,b)=>Number(b.id===ai.activeProvider)-Number(a.id===ai.activeProvider)):[{id:'default',name:'Default',baseUrl:ai.baseUrl,apiKey:ai.apiKey,models:ai.model?[ai.model]:[],reasoningModels:[],toolModels:[],enabled:true,kind:'openai'}]}
function finalReasoningText(value:unknown):string{const text=String(value||'').trim();if(!text)return'';const tagged=text.match(/<final>([\s\S]*?)<\/final>/i)?.[1]?.trim();if(tagged)return tagged;const withoutThink=text.replace(/<think>[\s\S]*?<\/think>/gi,'').trim();if(withoutThink&&withoutThink!==text)return withoutThink;const answer=text.match(/(?:final answer|پاسخ نهایی)\s*[:：]\s*([^\n]+(?:\n(?!\s*\n)[^\n]+)*)/i)?.[1]?.trim();if(answer)return answer;return text.split(/\n\s*\n/).filter(Boolean).at(-1)?.trim()||text}
export async function aiCall(provider:Provider,model:string,prompt:string){
  if(!provider.baseUrl||(!provider.apiKey&&provider.kind!=='ollama')||!model)throw Error('تنظیمات ارائه‌دهنده/مدل کامل نیست');
  const ai=(await loadConnections()).ai,kind=provider.kind||'openai',reasoning=provider.reasoningModels?.includes(model)||looksReasoningModel(model),toolsEnabled=provider.toolModels?.includes(model)&&kind!=='cloudflare',effectivePrompt=reasoning?prompt+'\n\nپس از تحلیل، پاسخ قابل استفاده را کوتاه و روشن داخل <final> و </final> بنویس.':prompt,endpoint=kind==='ollama'?provider.baseUrl+(provider.baseUrl.includes('/api/chat')?'':'/api/chat'):kind==='cloudflare'?provider.baseUrl.replace(/\/$/,'')+(provider.baseUrl.replace(/\/$/,'').endsWith('/ai/run')?'/'+model:''):provider.baseUrl+(provider.baseUrl.includes('/chat/completions')?'':'/chat/completions'),messages:any[]=[{role:'user',content:effectivePrompt}],started=Date.now(),headers:Record<string,string>={'content-type':'application/json'},toolTrace:ToolCallTrace[]=[];
  if(provider.apiKey)headers.authorization=`Bearer ${provider.apiKey}`;
  let body:any=null,response:Response|null=null;
  for(let round=0;round<(toolsEnabled?5:1);round++){
    const payload:any=kind==='ollama'?{model,messages,stream:false,options:reasoning?{num_predict:1200}:undefined}:kind==='cloudflare'?{messages,max_tokens:reasoning?1200:200}:{model,messages,max_tokens:reasoning?1200:400,...(reasoning?{}:{temperature:.2})};
    if(toolsEnabled){payload.tools=AI_TOOL_DEFINITIONS;payload.tool_choice='auto'}
    response=await networkFetch(endpoint,{method:'POST',headers,body:JSON.stringify(payload)},ai.network);body=await response.json().catch(()=>null);
    if(!response.ok){const error:any=new Error(`HTTP ${response.status}: ${body?.error?.message||body?.message||'AI error'}`);error.details={httpCode:response.status,raw:body,endpoint,kind,reasoning,toolsEnabled,toolTrace};throw error}
    const message=body?.choices?.[0]?.message||body?.message||{},calls=Array.isArray(message.tool_calls)?message.tool_calls:[];
    if(!toolsEnabled||!calls.length)break;
    messages.push({role:'assistant',content:message.content||'',tool_calls:calls});
    for(const call of calls.slice(0,8)){
      const name=String(call?.function?.name||call?.name||''),rawArgs=call?.function?.arguments??call?.arguments??{},args=typeof rawArgs==='string'?safeJson(rawArgs):rawArgs,trace=await executeAiTool(name,args);toolTrace.push(trace);messages.push({role:'tool',tool_call_id:call.id||name,name,content:JSON.stringify(trace.result).slice(0,30000)})
    }
  }
  const message=body?.choices?.[0]?.message||body?.message||{},reasoningText=message?.reasoning_content||message?.reasoning||body?.reasoning||'',content=message?.content||body?.result?.response||body?.response||'',value=reasoning?finalReasoningText(String(content).trim()||reasoningText):String(content).trim()||finalReasoningText(reasoningText);
  if(!value)throw Object.assign(new Error('مدل پاسخ نهایی قابل استفاده‌ای برنگرداند.'),{details:{httpCode:response?.status,raw:body,endpoint,kind,reasoning,toolsEnabled,toolTrace}});
  return{ok:true,text:value,reasoning:reasoningText?String(reasoningText):'',isReasoning:reasoning,toolsEnabled,toolTrace,latencyMs:Date.now()-started,provider:provider.id,model,httpCode:response?.status,kind,endpoint,raw:body}
}
function safeJson(value:string){try{return JSON.parse(value)}catch{return{raw:value}}}
export async function discoverProviderModels(providerId:string){const provider=(await aiProviders()).find(p=>p.id===providerId);if(!provider)throw Error('ارائه‌دهنده پیدا نشد');const ai=(await loadConnections()).ai,base=provider.baseUrl.replace(/\/chat\/completions\/?$/i,'').replace(/\/$/,''),endpoint=base+'/models',headers:Record<string,string>={accept:'application/json'};if(provider.apiKey)headers.authorization=`Bearer ${provider.apiKey}`;const response=await networkFetch(endpoint,{headers},ai.network),body=await response.json().catch(()=>null) as any;if(!response.ok)throw Object.assign(new Error(`HTTP ${response.status}: ${body?.error?.message||body?.message||'model discovery failed'}`),{details:{httpCode:response.status,raw:body,endpoint}});const rows=Array.isArray(body?.data)?body.data:Array.isArray(body?.models)?body.models:[],models=rows.filter((m:any)=>m?.capabilities?.completion_chat!==false&&!/(embed|moderation|ocr|transcri|audio|voxtral)/i.test(String(m?.id||m?.name||''))).map((m:any)=>String(m?.id||m?.name||'')).filter(Boolean);return{ok:true,provider:provider.id,endpoint,models:[...new Set(models)],rawCount:rows.length}}
export async function testAllModels(prompt='سلام',onlyCandidates=false){return runTests({prompt,onlyCandidates})}
export async function runTests(options:AiTestOptions={}){const ai=(await loadConnections()).ai,providers=await aiProviders(),wanted=new Set(ai.candidates),previous=await getState<any>('ai_test_results',{results:[]}),tested=new Set((previous.results||[]).filter((x:any)=>x.ok).map((x:any)=>x.key)),limit=Math.max(1,Math.min(500,Number(options.perProvider)||500)),tasks=providers.filter(p=>p.enabled).flatMap(p=>p.models.slice(0,limit).map(model=>({p,model,key:`${p.id}::${model}`}))).filter(x=>(!options.onlyCandidates||wanted.has(x.key))&&(!options.onlyUntested||!tested.has(x.key))),results:any[]=[];let cursor=0;await Promise.all(Array.from({length:Math.min(3,tasks.length)},async()=>{while(cursor<tasks.length){const task=tasks[cursor++];try{const chat=await aiCall(task.p,task.model,options.prompt||'سلام');let category:any=null;if(options.categoryTitle)try{category=await aiCall(task.p,task.model,`برای محصول «${options.categoryTitle}» فقط نام دسته مناسب را بنویس.`)}catch{}results.push({...chat,key:task.key,providerName:task.p.name,msgResponse:chat.text,catResponse:category?.text||'',category:category?.text||''})}catch(error){results.push({ok:false,key:task.key,provider:task.p.id,providerName:task.p.name,model:task.model,error:error instanceof Error?error.message:String(error),details:(error as any)?.details||null})}if(options.delayMs)await sleep(Math.min(60000,Math.max(0,options.delayMs)))}}));await setState('ai_test_results',{at:new Date().toISOString(),results});return results}
export async function startAiTest(options:AiTestOptions={}){const current=await getState<any>('ai_test_state',{});if(current.running&&Date.now()-Date.parse(current.startedAt||0)<2*3600000)throw Error('یک تست مدل در حال اجرا است');const id=crypto.randomUUID(),state={id,running:true,stop:false,startedAt:new Date().toISOString(),options,results:[],error:''};await setState('ai_test_state',state);void(async()=>{try{const results=await runTestsWithProgress(id,options);const latest=await getState<any>('ai_test_state',{});await setState('ai_test_results',{at:new Date().toISOString(),results});await setState('ai_test_state',{...latest,running:false,done:true,finishedAt:new Date().toISOString(),results})}catch(error){const latest=await getState<any>('ai_test_state',{});await setState('ai_test_state',{...latest,running:false,done:true,error:error instanceof Error?error.message:String(error),finishedAt:new Date().toISOString()})}})();return state}
async function runTestsWithProgress(id:string,options:AiTestOptions){const ai=(await loadConnections()).ai,providers=await aiProviders(),wanted=new Set(ai.candidates),previous=await getState<any>('ai_test_results',{results:[]}),tested=new Set((previous.results||[]).filter((x:any)=>x.ok).map((x:any)=>x.key)),limit=Math.max(1,Math.min(500,Number(options.perProvider)||50)),tasks=providers.filter(p=>p.enabled).flatMap(p=>p.models.slice(0,limit).map(model=>({p,model,key:`${p.id}::${model}`}))).filter(x=>(!options.onlyCandidates||wanted.has(x.key))&&(!options.onlyUntested||!tested.has(x.key))),results:any[]=[];for(let i=0;i<tasks.length;i++){const state=await getState<any>('ai_test_state',{});if(state.id!==id||state.stop)break;const task=tasks[i];try{const chat=await aiCall(task.p,task.model,options.prompt||'سلام');let category:any=null;if(options.categoryTitle)try{category=await aiCall(task.p,task.model,`برای محصول «${options.categoryTitle}» فقط نام دسته مناسب را بنویس.`)}catch{}results.push({...chat,key:task.key,providerName:task.p.name,msgResponse:chat.text,catResponse:category?.text||'',category:category?.text||''})}catch(error){results.push({ok:false,key:task.key,provider:task.p.id,providerName:task.p.name,model:task.model,error:error instanceof Error?error.message:String(error),details:(error as any)?.details||null})}await setState('ai_test_state',{...state,current:i+1,total:tasks.length,last:task.key,results});if(options.delayMs)await sleep(Math.min(60000,Math.max(0,options.delayMs)))}return results}
export async function aiTestState(){return getState<any>('ai_test_state',{running:false,done:false,results:[]})}
export async function stopAiTest(){const state=await aiTestState();await setState('ai_test_state',{...state,stop:true});return{ok:true}}
export async function candidateTest(task:'category'|'autoreply',input:string){const ai=(await loadConnections()).ai,providers=await aiProviders(),map=new Map(providers.map(p=>[p.id,p])),results=[];for(const key of ai.candidates){const [providerId,...rest]=key.split('::'),provider=map.get(providerId),model=rest.join('::');if(!provider)continue;const prompt=task==='category'?`برای محصول «${input}» فقط دسته مناسب را بنویس.`:`به پیام مشتری کوتاه و مؤدبانه پاسخ بده: ${input}`;try{results.push({...await aiCall(provider,model,prompt),key})}catch(error){results.push({ok:false,key,error:error instanceof Error?error.message:String(error),details:(error as any)?.details||null})}}return{task,input,master:ai.master,results}}
export async function networkDiagnostics(){const ai=(await loadConnections()).ai,provider=(await aiProviders()).find(p=>p.enabled),checks:any[]=[];if(!provider)return{ok:false,checks,error:'ارائه‌دهنده فعال نیست'};for(const mode of ['direct','doh','dns','proxy','worker']){const network={...ai.network,mode};if(mode==='doh'&&!network.dohUrl||mode==='dns'&&!network.resolveIp||mode==='proxy'&&!network.proxyUrl||mode==='worker'&&!network.workerUrl)continue;try{const started=Date.now(),endpoint=provider.baseUrl.replace(/\/$/,'');const response=await networkFetch(endpoint,{method:'GET',headers:provider.apiKey?{authorization:`Bearer ${provider.apiKey}`}:{},},network);checks.push({mode,ok:response.status<500,code:response.status,latencyMs:Date.now()-started})}catch(error){checks.push({mode,ok:false,error:error instanceof Error?error.message:String(error),details:(error as any)?.details||null})}}return{ok:checks.some(x=>x.ok),checks}}
export async function recordVote(task:string,winner:string,candidates:string[]){const votes=await getState<any>('ai_votes',{scores:{},history:[]});for(const key of candidates){votes.scores[key]??={wins:0,tests:0};votes.scores[key].tests++;if(key===winner)votes.scores[key].wins++}votes.history.push({at:new Date().toISOString(),task,winner,candidates});votes.history=votes.history.slice(-1000);await setState('ai_votes',votes);return leaderboard(votes)}
export async function getLeaderboard(){return leaderboard(await getState<any>('ai_votes',{scores:{},history:[]}))}
function leaderboard(votes:any){return Object.entries(votes.scores||{}).map(([key,v]:any)=>({key,wins:v.wins||0,tests:v.tests||0,score:v.tests?Math.round(v.wins/v.tests*1000)/10:0})).sort((a,b)=>b.score-a.score||b.wins-a.wins)}
async function networkFetch(url:string,init:RequestInit,net:Network):Promise<Response>{await assertPublicUrl(url);if(net.mode==='worker'&&net.workerUrl){const target=net.workerUrl.includes('{url}')?net.workerUrl.replace('{url}',encodeURIComponent(url)):net.workerUrl+(net.workerUrl.includes('?')?'&':'?')+'url='+encodeURIComponent(url);return safeFetch(target,init,3_000_000)}if(net.mode==='proxy'&&net.proxyUrl)return undiciFetch(url,{...(init as any),dispatcher:new ProxyAgent(net.proxyUrl)}) as unknown as Response;if((net.mode==='dns'||net.mode==='doh')&&(net.resolveIp||net.dohUrl)){const host=new URL(url).hostname,ip=net.resolveIp||await doh(host,net.dohUrl);if(privateIp(ip))throw Error('IP خصوصی برای اتصال دستی/DoH مجاز نیست');const dispatcher=new Agent({connect:{lookup(_host:any,options:any,callback:any){const family=ip.includes(':')?6:4;options?.all?callback(null,[{address:ip,family}]):callback(null,ip,family)}} as any});return undiciFetch(url,{...(init as any),dispatcher}) as unknown as Response}return safeFetch(url,init,3_000_000)}
async function doh(host:string,url:string){const endpoint=url+(url.includes('?')?'&':'?')+'name='+encodeURIComponent(host)+'&type=A',r=await safeFetch(endpoint,{headers:{accept:'application/dns-json'}},500_000),j=await r.json() as any,ip=(j.Answer||[]).find((x:any)=>x.type===1)?.data;if(!ip)throw Error('DoH پاسخی برای دامنه نداد');return String(ip)}
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
