export function setupPage(error: string): string {
  const safeError = escapeHtml(error);
  return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>راه‌اندازی Scraper 4</title><style>:root{color-scheme:dark}body{margin:0;background:#07111e;color:#e8eef8;font:15px Tahoma;line-height:2}main{max-width:780px;margin:40px auto;padding:25px}.card{background:#101e31;border:1px solid #29415f;border-radius:15px;padding:22px;margin-top:15px}h1{color:#38bdf8}code,pre{direction:ltr;text-align:left;background:#050b13;border-radius:8px;padding:10px;display:block;overflow:auto}.error{color:#fda4af;border-color:#be123c}b{color:#fcd34d}</style></head><body><main><h1>Scraper 4 روی Render اجرا شد</h1><div class="card error"><b>پایگاه داده هنوز متصل نیست</b><br>${safeError}</div><div class="card"><h2>راه‌اندازی در سه مرحله</h2><ol><li>در Render گزینه <b>New → PostgreSQL</b> را انتخاب و یک دیتابیس بسازید.</li><li>در صفحه دیتابیس مقدار <b>Internal Database URL</b> را کپی کنید.</li><li>در Web Service به <b>Environment</b> بروید و متغیر زیر را اضافه کنید:</li></ol><pre>DATABASE_URL = Internal Database URL</pre><p>همچنین یک مقدار تصادفی طولانی برای متغیر زیر تعریف کنید:</p><pre>ADMIN_TOKEN = a-long-random-secret</pre><p>پس از Save Changes، سرویس خودکار Restart می‌شود و جداول را می‌سازد.</p></div><div class="card"><b>نکته:</b> فایل render.yaml فقط هنگام ساخت سرویس از طریق Blueprint منابع را خودکار ایجاد می‌کند. اتصال یک Web Service موجود به GitHub باعث اجرای خودکار Blueprint نمی‌شود.</div></main></body></html>`;
}

export const DASHBOARD = `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scraper 4 Render</title><style>
:root{color-scheme:dark;--bg:#07111e;--card:#101e31;--line:#29415f;--muted:#91a7c1;--blue:#38bdf8;--green:#34d399;--red:#fb7185}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#123757,var(--bg) 38%);font:14px Tahoma;color:#e8eef8}main{max-width:1100px;margin:auto;padding:22px}.top,.row{display:flex;align-items:center;justify-content:space-between;gap:10px}h1 b{color:var(--blue)}.card{background:#101e31ee;border:1px solid var(--line);border-radius:14px;padding:17px;margin-top:14px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.five{grid-template-columns:2fr repeat(4,1fr)}label{display:block;color:var(--muted);font-size:12px;margin-bottom:4px}input,select,button{width:100%;padding:9px;border-radius:8px;border:1px solid #34506e;background:#081522;color:#e8eef8;font:inherit}button{cursor:pointer;background:#075985;border-color:#0ea5e9;font-weight:bold}button:disabled{opacity:.55;cursor:wait}.green{background:#065f46}.red{background:#881337}.actions{display:flex;gap:6px}.actions button{width:auto}.item{padding:11px;border:1px solid #263e58;background:#081522;border-radius:9px;margin-top:8px}.item small{display:block;color:var(--muted);direction:ltr}.status{position:sticky;top:8px;z-index:10;padding:12px 15px;border-radius:10px;background:#17263b;border:1px solid #365472;margin-top:12px;display:none}.status.show{display:block}.status.ok{border-color:#059669;color:#a7f3d0}.status.error{border-color:#e11d48;color:#fecdd3}.log{white-space:pre-wrap;background:#040b13;padding:12px;border-radius:9px;min-height:80px;max-height:400px;overflow:auto}@media(max-width:720px){.grid,.five{grid-template-columns:1fr}.top,.row{align-items:stretch;flex-direction:column}.actions{flex-wrap:wrap}}
</style></head><body><main><div class="top"><h1>اسکرپر <b>۴</b> روی Render</h1><span>Node.js · Hono · PostgreSQL · Cheerio</span></div><div id="notice" class="status" role="status"></div><div class="card grid"><div><label>ADMIN_TOKEN</label><input id="token" type="password" autocomplete="current-password"></div><button id="connectBtn" type="button">اتصال و بررسی</button></div><div class="card"><h2>پروفایل جدید</h2><div class="grid"><div><label>نام</label><input id="name"></div><div><label>URL</label><input id="url" dir="ltr" placeholder="https://example.com/shop"></div></div><div class="grid five" style="margin-top:10px"><div><label>محصول</label><input id="container" value="li.product" dir="ltr"></div><div><label>عنوان</label><input id="title" value="h2" dir="ltr"></div><div><label>قیمت</label><input id="price" value=".price" dir="ltr"></div><div><label>لینک</label><input id="link" value="a[href]" dir="ltr"></div><div><label>تصویر</label><input id="image" value="img" dir="ltr"></div></div><div class="grid" style="margin-top:10px"><div><label>تعداد صفحات</label><input id="pages" type="number" value="1" min="1" max="100"></div><div><label>اجرای دوره‌ای، دقیقه (۰=خاموش)</label><input id="interval" type="number" value="0" min="0"></div></div><button id="saveBtn" type="button" class="green" style="margin-top:10px">ذخیره پروفایل</button></div><div class="card"><h2>پروفایل‌ها</h2><div id="profiles">برای مشاهده، ابتدا توکن را وارد کنید.</div></div><div class="card"><h2>جزئیات وضعیت</h2><div id="out" class="log">آماده</div></div></main><script src="/dashboard.js" defer></script></body></html>`;

export const DASHBOARD_JS = `
'use strict';
const $ = id => document.getElementById(id);
const token = () => $('token').value.trim();
const headers = () => ({ 'content-type':'application/json', authorization:'Bearer ' + token() });
function notice(message, kind='ok') { const el=$('notice'); el.className='status show '+kind; el.textContent=message; }
function output(value) { $('out').textContent=typeof value==='string'?value:JSON.stringify(value,null,2); }
function busy(button, state) { button.disabled=state; if(state){button.dataset.label=button.textContent;button.textContent='در حال انجام…'}else if(button.dataset.label)button.textContent=button.dataset.label; }
async function api(path, options={}) { const response=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}}); const text=await response.text(); let data; try{data=JSON.parse(text)}catch{data={error:text||('HTTP '+response.status)}} if(!response.ok)throw new Error(data.detail||data.error||('HTTP '+response.status)); return data; }
async function load() { const button=$('connectBtn'); busy(button,true); try { if(!token())throw new Error('ابتدا ADMIN_TOKEN را وارد کنید.'); localStorage.setItem('s4rt',token()); const data=await api('/api/profiles'); renderProfiles(data.profiles); const status=await api('/api/status'); output(status); notice('اتصال برقرار شد. '+data.profiles.length+' پروفایل بارگذاری شد.'); } catch(error) { notice(error.message,'error'); output({error:error.message}); } finally { busy(button,false); } }
function renderProfiles(profiles) { $('profiles').innerHTML=profiles.map(p=>'<div class="item row"><div><b>'+escapeHtml(p.name)+'</b><small>'+escapeHtml(p.url)+'</small></div><div class="actions"><button type="button" data-action="scrape" data-id="'+escapeAttr(p.id)+'">استخراج</button><button type="button" class="green" data-action="sync" data-id="'+escapeAttr(p.id)+'">ارسال</button><button type="button" class="red" data-action="delete" data-id="'+escapeAttr(p.id)+'">حذف</button></div></div>').join('')||'هنوز پروفایلی ذخیره نشده است.'; }
async function saveProfile() { const button=$('saveBtn'); busy(button,true); try { if(!token())throw new Error('ابتدا ADMIN_TOKEN را وارد و اتصال را بررسی کنید.'); if(!$('url').value.trim())throw new Error('آدرس پروفایل اجباری است.'); const body={name:$('name').value.trim(),url:$('url').value.trim(),pages:Number($('pages').value),intervalMinutes:Number($('interval').value),selectors:{container:$('container').value.trim(),title:$('title').value.trim(),price:$('price').value.trim(),link:$('link').value.trim(),image:$('image').value.trim()}}; const saved=await api('/api/profiles',{method:'POST',body:JSON.stringify(body)}); notice('پروفایل «'+saved.profile.name+'» ذخیره شد.'); output(saved); await load(); } catch(error) { notice(error.message,'error'); output({error:error.message}); } finally { busy(button,false); } }
async function act(action,id) { try { if(action==='delete'){if(!confirm('پروفایل حذف شود؟'))return; await api('/api/profiles/'+encodeURIComponent(id),{method:'DELETE'});notice('پروفایل حذف شد.');await load();return} const endpoint=action==='scrape'?'/scrape':'/sync'; const body=action==='sync'?{target:'both'}:{}; const data=await api('/api/profiles/'+encodeURIComponent(id)+endpoint,{method:'POST',body:JSON.stringify(body)}); notice('کار در صف قرار گرفت.');output(data);watch(data.job.id); } catch(error){notice(error.message,'error');output({error:error.message})} }
function watch(id){const timer=setInterval(async()=>{try{const data=await api('/api/jobs/'+id);output(data.job);if(!['queued','running'].includes(data.job.status)){clearInterval(timer);notice(data.job.status==='done'?'عملیات تمام شد.':'عملیات با وضعیت '+data.job.status+' پایان یافت.',data.job.status==='done'?'ok':'error')}}catch(error){clearInterval(timer);notice(error.message,'error')}},1500)}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function escapeAttr(value){return escapeHtml(value)}
$('connectBtn').addEventListener('click',load); $('saveBtn').addEventListener('click',saveProfile); $('profiles').addEventListener('click',event=>{const button=event.target.closest('button[data-action]');if(button)act(button.dataset.action,button.dataset.id)}); $('token').addEventListener('keydown',event=>{if(event.key==='Enter')load()}); $('token').value=localStorage.getItem('s4rt')||''; if($('token').value)load();
`;

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[char] || char);
}
