import { createCipheriv,createDecipheriv,randomBytes,scryptSync } from 'node:crypto';
import { config } from './config.js';
import { loadConnections } from './connections.js';
import { createPhpSettingsBundle } from './settings-transfer.js';
import { getState, setState } from './db.js';
import { safeFetch } from './network.js';

const api='https://api.github.com';
async function cfg(){const c=(await loadConnections(true)).github;if(!c.token||!/^[-\w.]+\/[-\w.]+$/.test(c.repo))throw Error('توکن یا مخزن GitHub در منوی نسخه کد کامل نیست');return c}
function headers(token:string,accept='application/vnd.github+json'){return{authorization:`Bearer ${token}`,accept,'user-agent':'scraper4-render-backup','x-github-api-version':'2022-11-28'}}
function filePath(path:string,name:string){return[path,name].filter(Boolean).join('/').split('/').map(encodeURIComponent).join('/')}
function timestamp(){const value=new Date().toISOString().replace(/\D/g,'').slice(0,14);return`${value.slice(0,8)}_${value.slice(8)}`}
export async function githubBackupRun(host='render'){const c=await cfg(),bundle=await createPhpSettingsBundle(host),stamp=timestamp(),name=`settings_${stamp}.json`,path=filePath(c.path,name),url=`${api}/repos/${c.repo}/contents/${path}`,existing=await safeFetch(`${url}?ref=${encodeURIComponent(c.branch)}`,{headers:headers(c.token)},2_000_000),old=existing.ok?await existing.json() as any:null,payload:any={message:`Scraper 4 settings backup ${stamp}`,content:Buffer.from(JSON.stringify(sealBackup(JSON.stringify(bundle)))).toString('base64'),branch:c.branch};if(old?.sha)payload.sha=old.sha;const response=await safeFetch(url,{method:'PUT',headers:{...headers(c.token),'content-type':'application/json'},body:JSON.stringify(payload)},3_000_000),body=await response.json().catch(()=>null) as any;if(!response.ok)throw Error(`GitHub backup HTTP ${response.status}: ${body?.message||'unknown'}`);const result={ok:true,name,path,sha:body?.content?.sha,url:body?.content?.html_url,bytes:bundle.total_bytes,at:new Date().toISOString()};await setState('github_backup_last',result);return result}
export async function githubBackupList(){const c=await cfg(),path=c.path.split('/').filter(Boolean).map(encodeURIComponent).join('/'),url=`${api}/repos/${c.repo}/contents/${path}?ref=${encodeURIComponent(c.branch)}`,response=await safeFetch(url,{headers:headers(c.token)},5_000_000);if(response.status===404)return{ok:true,items:[]};const body=await response.json() as any;if(!response.ok)throw Error(`GitHub list HTTP ${response.status}: ${body?.message||''}`);const items=(Array.isArray(body)?body:[]).filter(x=>x.type==='file'&&/^settings_\d{8}(?:_?\d{6})\.json$/.test(x.name)).map(x=>({name:x.name,path:x.path,size:x.size,sha:x.sha,downloadUrl:x.download_url,htmlUrl:x.html_url})).sort((a,b)=>b.name.localeCompare(a.name));return{ok:true,items}}
export async function githubBackupGet(name:string){if(!/^settings_\d{8}(?:_?\d{6})\.json$/.test(name))throw Error('نام فایل بکاپ معتبر نیست');const c=await cfg(),path=filePath(c.path,name),url=`${api}/repos/${c.repo}/contents/${path}?ref=${encodeURIComponent(c.branch)}`,response=await safeFetch(url,{headers:headers(c.token)},30_000_000),body=await response.json() as any;if(!response.ok)throw Error(`GitHub download HTTP ${response.status}: ${body?.message||''}`);const text=Buffer.from(String(body.content||'').replace(/\n/g,''),'base64').toString('utf8'),parsed=JSON.parse(text);return parsed?.app==='scraper4-render-encrypted-backup'?JSON.parse(openBackup(parsed)):parsed}
export async function githubBackupStatus(){return getState('github_backup_last',null)}
function backupKey(salt:Buffer){if(!config.adminToken)throw Error('ADMIN_TOKEN برای رمزنگاری بکاپ لازم است');return scryptSync(config.adminToken,salt,32)}
export function sealBackup(text:string){const salt=randomBytes(16),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',backupKey(salt),iv),data=Buffer.concat([cipher.update(text,'utf8'),cipher.final()]);return{app:'scraper4-render-encrypted-backup',version:1,salt:salt.toString('base64'),iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),ciphertext:data.toString('base64')}}
export function openBackup(value:any){try{const salt=Buffer.from(value.salt,'base64'),decipher=createDecipheriv('aes-256-gcm',backupKey(salt),Buffer.from(value.iv,'base64'));decipher.setAuthTag(Buffer.from(value.tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(value.ciphertext,'base64')),decipher.final()]).toString('utf8')}catch{throw Error('رمزگشایی بکاپ GitHub ممکن نشد؛ ADMIN_TOKEN تغییر کرده است؟')}}
