import { aiCall, aiProviders } from './ai.js';
import { loadConnections } from './connections.js';
import { maintenanceRows } from './db.js';
import { fixBasalamCategory, rejectedBasalam } from './maintenance.js';
import { safeFetch } from './network.js';

const norm=(value:string)=>value.toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();
type Category={id:number;name:string;parentId:number|null;leaf:boolean};
export async function basalamCategories():Promise<Category[]>{const c=(await loadConnections()).basalam;if(!c.token)throw Error('توکن باسلام خالی است');const r=await safeFetch(`${c.api}/categories`,{headers:{authorization:`Bearer ${c.token}`,accept:'application/json'}},8_000_000),body=await r.json() as any;if(!r.ok)throw Error(`Basalam categories HTTP ${r.status}`);const raw=body?.data?.categories||body?.data||body?.categories||body;return flattenCategories(Array.isArray(raw)?raw:[])}
function flattenCategories(rows:any[],parentId:number|null=null,out:Category[]=[]){for(const row of rows){const id=Number(row.id||row.category_id),children=row.children||row.subcategories||row.childs||[];if(id)out.push({id,name:String(row.name||row.title||''),parentId:Number(row.parent_id||parentId)||null,leaf:!children.length});if(Array.isArray(children))flattenCategories(children,id,out)}return out}
export function rankCategoryCandidates(title:string,categories:Category[],limit=250){const words=norm(title).split(' ').filter(x=>x.length>1),ranked=categories.map(category=>({category,score:words.reduce((n,w)=>n+(norm(category.name).includes(w)?1:0),0)})).sort((a,b)=>b.score-a.score);return(ranked.some(x=>x.score>0)?ranked.filter(x=>x.score>0):ranked).slice(0,limit).map(x=>x.category)}
export async function recommendCategory(title:string,description='',categories?:Category[]){const all=categories||await basalamCategories(),leaf=all.filter(x=>x.leaf||!all.some(y=>y.parentId===x.id)),providers=await aiProviders(),provider=providers.find(x=>x.enabled&&x.models.length);if(!provider)throw Error('مدل فعال هوش مصنوعی وجود ندارد');const candidates=rankCategoryCandidates(title,leaf),list=candidates.map(x=>`${x.id}: ${x.name}`).join('\n'),prompt=`برای محصول زیر بهترین دسته باسلام را انتخاب کن. فقط شناسه عددی را بنویس.\nعنوان: ${title}\nتوضیح: ${description.slice(0,800)}\nدسته‌ها:\n${list}`,response=await aiCall(provider,provider.models[0],prompt),id=Number(response.text.match(/\d+/)?.[0]||0),category=leaf.find(x=>x.id===id);return{ok:Boolean(category),title,categoryId:category?.id||0,categoryName:category?.name||'',raw:response.text,provider:provider.id,model:provider.models[0],latencyMs:response.latencyMs}}
export async function batchRejectedCategories(options:{limit?:number;apply?:boolean}={}){const [items,categories]=await Promise.all([rejectedBasalam(),basalamCategories()]),selected=items.slice(0,Math.min(200,Math.max(1,Number(options.limit)||20))),results:any[]=[];for(const item of selected){try{const result=await recommendCategory(item.title,String(item.reason||''),categories);if(options.apply&&result.categoryId)await fixBasalamCategory(item.id,result.categoryId);results.push({...item,...result,applied:Boolean(options.apply&&result.categoryId)})}catch(error){results.push({...item,ok:false,error:error instanceof Error?error.message:String(error)})}}return{ok:results.every(x=>x.ok),apply:Boolean(options.apply),total:items.length,processed:results.length,applied:results.filter(x=>x.applied).length,results}}
export async function classifyLocalProducts(profileId:string,limit=20){const rows=(await maintenanceRows(profileId)).filter(x=>x.active&&!x.data?.category).slice(0,Math.min(200,Math.max(1,limit))),categories=await basalamCategories(),results:any[]=[];for(const row of rows)try{results.push({profileId:row.profile_id,sourceKey:row.source_key,...await recommendCategory(row.title,row.data?.shortDesc||'',categories)})}catch(error){results.push({profileId:row.profile_id,sourceKey:row.source_key,title:row.title,ok:false,error:error instanceof Error?error.message:String(error)})}return{ok:true,total:rows.length,results}}
