import { Agent,ProxyAgent,fetch as undiciFetch } from 'undici';
import { loadConnections } from './connections.js';
import { assertPublicUrl,privateIp,safeFetch } from './network.js';

type SourceNetwork={mode:string;proxyUrl:string;proxyAuth:string;workerUrl:string;dohUrl:string;resolveIp:string;fallback:boolean;timeoutSeconds:number};
export async function sourceFetch(raw:string,init:RequestInit={},maxBytes=8_000_000,forceDirect=false):Promise<Response>{const config=(await loadConnections()).sourceNetwork;if(forceDirect||!config||config.mode==='direct')return safeFetch(raw,init,maxBytes);try{return await routedFetch(raw,init,maxBytes,config)}catch(error){if(config.fallback)return safeFetch(raw,init,maxBytes);throw error}}
export async function sourceText(raw:string,maxBytes=8_000_000,forceDirect=false){const response=await sourceFetch(raw,{},maxBytes,forceDirect);if(!response.ok)throw Error(`HTTP ${response.status} from ${raw}`);const buffer=await response.arrayBuffer();if(buffer.byteLength>maxBytes)throw Error(`Response exceeds ${maxBytes} bytes`);return{text:new TextDecoder().decode(buffer),url:response.url||raw,mode:forceDirect?'direct':(await loadConnections()).sourceNetwork.mode}}
export async function sourceDiagnostics(raw:string){const config=(await loadConnections()).sourceNetwork,modes=['direct','doh','dns','proxy','worker'],checks:any[]=[];for(const mode of modes){if(mode==='doh'&&!config.dohUrl||mode==='dns'&&!config.resolveIp||mode==='proxy'&&!config.proxyUrl||mode==='worker'&&!config.workerUrl)continue;const started=Date.now();try{const response=mode==='direct'?await safeFetch(raw,{},1_000_000):await routedFetch(raw,{},1_000_000,{...config,mode});checks.push({mode,ok:response.ok,code:response.status,latencyMs:Date.now()-started,url:response.url})}catch(error){checks.push({mode,ok:false,latencyMs:Date.now()-started,error:error instanceof Error?error.message:String(error)})}}return{ok:checks.some(x=>x.ok),checks}}
async function routedFetch(raw:string,init:RequestInit,maxBytes:number,config:SourceNetwork){let url=(await assertPublicUrl(raw)).href;if(config.mode==='worker'){const target=config.workerUrl.includes('{url}')?config.workerUrl.replace('{url}',encodeURIComponent(url)):config.workerUrl+(config.workerUrl.includes('?')?'&':'?')+'url='+encodeURIComponent(url);return safeFetch(target,init,maxBytes)}let dispatcher:any;if(config.mode==='proxy'){let proxy=config.proxyUrl;if(config.proxyAuth&&!new URL(proxy).username){const u=new URL(proxy),[user,password='']=config.proxyAuth.split(':');u.username=user;u.password=password;proxy=u.href}dispatcher=new ProxyAgent(proxy)}else if(config.mode==='dns'||config.mode==='doh'){const host=new URL(url).hostname,ip=config.resolveIp||await doh(host,config.dohUrl);if(privateIp(ip))throw Error('IP خصوصی در مسیر شبکه مبدأ مجاز نیست');dispatcher=new Agent({connect:{lookup(_host:any,options:any,callback:any){const family=ip.includes(':')?6:4;options?.all?callback(null,[{address:ip,family}]):callback(null,ip,family)}} as any})}else return safeFetch(url,init,maxBytes);for(let redirect=0;redirect<5;redirect++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Math.max(5,config.timeoutSeconds||45)*1000);try{const response=await undiciFetch(url,{...(init as any),dispatcher,redirect:'manual',signal:controller.signal,headers:{'user-agent':'Mozilla/5.0 (compatible; Scraper4Render/2)',accept:'text/html,application/json;q=0.9,*/*;q=0.8',...(init.headers||{})}});if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');if(!location)throw Error('Redirect without location');url=(await assertPublicUrl(new URL(location,url).href)).href;continue}const length=Number(response.headers.get('content-length')||0);if(length>maxBytes)throw Error(`Response exceeds ${maxBytes} bytes`);return response as unknown as Response}finally{clearTimeout(timer)}}throw Error('Too many redirects')}
async function doh(host:string,url:string){const endpoint=url+(url.includes('?')?'&':'?')+'name='+encodeURIComponent(host)+'&type=A',response=await safeFetch(endpoint,{headers:{accept:'application/dns-json'}},500_000),body=await response.json() as any,ip=(body.Answer||[]).find((x:any)=>x.type===1)?.data;if(!ip)throw Error('DoH پاسخی برای دامنه نداد');return String(ip)}
