import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';

const read=path=>readFile(path,'utf8');

test('full-source parity audit reports mapped and missing contracts honestly',async()=>{const audit=JSON.parse(await read('parity-audit.json'));assert.equal(audit.summary.phpPostActions,28);assert.equal(audit.summary.postMissing,0);assert.equal(audit.summary.relevantGet,audit.summary.getCovered+audit.summary.getMissing);assert.deepEqual(audit.missing.get.sort(),audit.get.filter(x=>x.status==='missing').map(x=>x.name).sort())});
test('PHP hamburger inventory contains exactly 57 unique operations',async()=>{const source=await read('render-src/parity.ts'),ids=[...source.matchAll(/\{id:'([^']+)'/g)].map(x=>x[1]);assert.equal(ids.length,57);assert.equal(new Set(ids).size,57)});
test('every operational capability declares an endpoint or implementation note',async()=>{const source=await read('render-src/parity.ts'),rows=[...source.matchAll(/\{id:'([^']+)'[^\n]+status:'operational'([^\n]+)\}/g)];assert.ok(rows.length>40);for(const row of rows)assert.match(row[2],/endpoint:|note:|\}/)});
test('dashboard JavaScript parses and required element references exist',async()=>{const source=await read('render-src/dashboard.ts'),match=source.match(/export const DASHBOARD_JS = String\.raw`\n([\s\S]*?)\n`;/);assert.ok(match);new vm.Script(match[1]);const refs=[...match[1].matchAll(/\$\('([^']+)'\)/g)].map(x=>x[1]);for(const id of new Set(refs)){const dynamic=id.match(/^(?:sel|result|wrap)-(.+)$/);assert.ok(source.includes(`id=\\"${id}\\"`)||source.includes(`id="${id}"`)||(dynamic&&source.includes(`['${dynamic[1]}'`)),`missing #${id}`)}});
test('destructive maintenance endpoints require explicit confirmation',async()=>{const source=await read('render-src/server.ts');assert.match(source,/body\.confirm==='APPLY'/);assert.match(source,/\.confirm!=='SEND'/)});
test('source tree does not contain committed live credential assignments',async()=>{const files=['render-src/vault.ts','render-src/config.ts','render-src/dashboard.ts','render-src/server.ts'];for(const file of files){const source=await read(file);assert.doesNotMatch(source,/(?:apiKey|token|secret)\s*[:=]\s*['"][A-Za-z0-9_-]{20,}['"]/i,file)}});
test('all required Render subsystems are represented',async()=>{const source=await read('RENDER-PARITY.md');for(const term of ['خزانه','مغایرت','ویرایش گروهی','یادگیری دسته‌بندی','پاسخ خودکار','گزارش شبانه'])assert.ok(source.includes(term),term)});
test('application version is synchronized with package.json',async()=>{const source=await read('render-src/version.ts'),pkg=JSON.parse(await read('package.json')),version=source.match(/APP_VERSION = '([^']+)'/)?.[1];assert.equal(version,pkg.version);assert.match(source,/APP_BUILD_DATE/)});
test('comprehensive WooCommerce and Basalam managers support filters, editing and guarded batches',async()=>{const dashboard=await read('render-src/dashboard.ts'),server=await read('render-src/server.ts'),maintenance=await read('render-src/maintenance.ts');for(const id of ['pane-destination','destinationBody','destBatchOperation','destBatchPreview','destBatchApply','destDuplicates','destRejected'])assert.ok(dashboard.includes(id),id);for(const route of ['/api/destination/:target/products/:id','/api/destination/:target/batch','/api/destination/:target/overview','/api/destination/:target/duplicates'])assert.ok(server.includes(route),route);assert.match(maintenance,/destinationUpdate/);assert.match(maintenance,/destinationBatch/);assert.match(server,/body\.confirm==='APPLY'/)});
test('visual configuration editors and comprehensive diagnostics replace raw JSON workflows',async()=>{const dashboard=await read('render-src/dashboard.ts'),server=await read('render-src/server.ts'),ai=await read('render-src/ai.ts');for(const id of ['diagnosticModal','diagnosticRaw','basalamShopList','addBasalamShop','autoreplyRuleList','addAutoreplyRule','aiProviderName','aiProviderBaseUrl'])assert.ok(dashboard.includes(id),id);assert.match(server,/connectionDiagnostic/);assert.match(ai,/raw:body/);assert.ok(!dashboard.includes('id="importJson"'));assert.ok(!dashboard.includes('data-connection="basalam.shops"'))});
test('selector and AI sub-tabs are scoped independently',async()=>{const dashboard=await read('render-src/dashboard.ts');assert.match(dashboard,/\.sub-tab\[data-sub\]/);assert.match(dashboard,/\[data-ai-tab\]/);assert.doesNotMatch(dashboard,/querySelectorAll\('\.sub-tab'\)/)});
test('advanced visual selector studio has stable generation, DOM navigation and responsive controls',async()=>{const visual=await read('render-src/visual.ts'),dashboard=await read('render-src/dashboard.ts'),match=visual.match(/const PICKER_JS = String\.raw`([\s\S]*?)`;/);assert.ok(match);new vm.Script(match[1]);for(const id of ['__s4up','__s4down','__s4prev','__s4next','__s4open','__s4save'])assert.ok(visual.includes(id),id);for(const id of ['visualUndo','visualRedo','visualAutoNext','selectorCompletion'])assert.ok(dashboard.includes(id),id);assert.match(visual,/data-s4-href/);assert.match(visual,/data-testid/);assert.match(visual,/listModes/);assert.match(visual,/queryCount/)});
test('selected product queues persist keys and local editing is guarded',async()=>{const db=await read('render-src/db.ts'),processor=await read('render-src/processor.ts'),server=await read('render-src/server.ts'),dashboard=await read('render-src/dashboard.ts');assert.match(db,/payload jsonb/);assert.match(db,/payload\.keys/);assert.match(processor,/job\.payload\?\.keys/);assert.ok(server.includes("confirm')!=='ARCHIVE"));for(const id of ['selectAllProducts','syncSelectedProducts','selectedProductCount','batchSyncTarget'])assert.ok(dashboard.includes(id),id)});
test('queue engine has dedup locks, pause/resume, delayed retries and heartbeats',async()=>{const db=await read('render-src/db.ts'),processor=await read('render-src/processor.ts'),server=await read('render-src/server.ts'),dashboard=await read('render-src/dashboard.ts');assert.match(db,/pg_advisory_xact_lock/);assert.match(db,/available_at<=now\(\)/);assert.match(db,/attempts=attempts\+1/);assert.match(processor,/retry_wait/);assert.match(processor,/retryable\(job\.error\)/);assert.match(processor,/details \$\{detailDone\}/);for(const route of ['/api/queue/overview','/api/queue/pause','/api/queue/resume'])assert.ok(server.includes(route),route);for(const id of ['pauseQueue','resumeQueue','queueState'])assert.ok(dashboard.includes(id),id)});
test('professional reports expose filters, CSV, retention and ledger-backed digest',async()=>{const server=await read('render-src/server.ts'),dashboard=await read('render-src/dashboard.ts'),automation=await read('render-src/automation.ts');for(const route of ['/api/changes','/api/changes.csv','/api/reports'])assert.ok(server.includes(route),route);for(const id of ['pane-reports','reportHours','reportProfile','changesBody','exportChanges'])assert.ok(dashboard.includes(id),id);assert.match(automation,/changeReport/);assert.match(automation,/pruneProductChanges/)});
test('change ledger distinguishes added updated unchanged and removed products',async()=>{const db=await read('render-src/db.ts'),processor=await read('render-src/processor.ts'),server=await read('render-src/server.ts');assert.match(db,/CREATE TABLE IF NOT EXISTS product_changes/);assert.match(db,/sameProduct/);for(const type of ["'added'","'updated'","'unchanged'","'removed'"])assert.ok(db.includes(type),type);assert.match(processor,/unchanged\+\+/);assert.ok(server.includes('/api/jobs/:id/report'))});
test('source network routing covers direct, DoH, DNS, proxy, worker and profile override',async()=>{const transport=await read('render-src/source-network.ts'),processor=await read('render-src/processor.ts'),dashboard=await read('render-src/dashboard.ts');for(const mode of ["'direct'","'doh'","'dns'","'proxy'","'worker'"])assert.ok(transport.includes(mode),mode);assert.match(processor,/!profile\.netIndirect/);assert.ok(dashboard.includes('source-diagnostics'));assert.ok(dashboard.includes('netIndirect'))});
test('notification engine has preview, guarded send, selected delivery and flood-safe seeding',async()=>{const server=await read('render-src/server.ts'),automation=await read('render-src/automation.ts'),dashboard=await read('render-src/dashboard.ts');for(const route of ['/api/notifications/sweep','/api/notifications/selected','/api/notifications/state'])assert.ok(server.includes(route),route);assert.match(automation,/seeded:true/);assert.match(automation,/initialized:true/);for(const action of ['notify-preview','notify-send','notify-selected'])assert.ok(dashboard.includes(action),action)});
test('AI control center contains all five PHP-style tabs and background endpoints',async()=>{const dashboard=await read('render-src/dashboard.ts'),server=await read('render-src/server.ts');for(const tab of ['providers','test','models','candidates','network'])assert.ok(dashboard.includes(`data-ai-tab=\\"${tab}\\"`)||dashboard.includes(`data-ai-tab="${tab}"`),tab);for(const route of ['/api/ai/test-start','/api/ai/test-status','/api/ai/test-stop','/api/ai/candidates/:task','/api/ai/network-diagnostics'])assert.ok(server.includes(route),route);for(const id of ['aiResultsModal','aiStatTotal','aiStatOk','aiStatFail','aiStatLatency','aiStatSuccess','aiResultSearch','aiResultProvider','aiResultStatus','aiResultSort','aiResultExport'])assert.ok(dashboard.includes(`id=\\"${id}\\"`)||dashboard.includes(`id="${id}"`),id)});
test('legacy scraper4.php compatibility route is authenticated and fails explicitly',async()=>{const source=await read('render-src/server.ts');assert.match(source,/app\.use\('\/scraper4\.php'/);assert.match(source,/app\.all\('\/scraper4\.php',legacyHandler\)/);assert.match(source,/Legacy endpoint not ported/);for(const key of ['profiles','cron_run','backup_export','bsl_products','ai_test_all','ar_run','recon','photo_fix','suffix_report','gallery_suggest','image_proxy'])assert.ok(source.includes(`has('${key}')`),key)});
