import test from 'node:test';import assert from 'node:assert/strict';import {readFile,rm} from 'node:fs/promises';import {build} from 'esbuild';import * as cheerio from 'cheerio';
let modulePromise;
async function scraper(){if(!modulePromise)modulePromise=(async()=>{await build({entryPoints:['render-src/scraper.ts'],outfile:'.scraper-test.mjs',bundle:true,platform:'node',format:'esm',target:'node20',packages:'external'});return import(`../.scraper-test.mjs?${Date.now()}`)})();return modulePromise}
test.after(async()=>rm('.scraper-test.mjs',{force:true}));
test('product parser matches expected PHP-style selectors and Persian prices',async()=>{const m=await scraper(),html=await readFile('render-tests/fixtures/shop.html','utf8'),products=m.parseProductHtml(html,'https://shop.example/category/perfume',{container:'li.product',title:'h2.title',price:'.price',link:'a.product-link',image:'img'});assert.equal(products.length,2);assert.equal(products[0].title,'ادو پرفیوم زنانه');assert.equal(products[0].price,1250000);assert.equal(products[0].url,'https://shop.example/p/perfume-1');assert.equal(products[0].image,'https://shop.example/images/one.jpg');assert.equal(products[1].price,850000)});
test('product parser produces stable source keys',async()=>{const m=await scraper(),html=await readFile('render-tests/fixtures/shop.html','utf8'),selectors={container:'li.product',title:'h2.title',price:'.price',link:'a.product-link',image:'img'},a=m.parseProductHtml(html,'https://shop.example/',selectors),b=m.parseProductHtml(html,'https://shop.example/',selectors);assert.deepEqual(a.map(x=>x.sourceKey),b.map(x=>x.sourceKey))});
test('selectors may target the product container itself',async()=>{const m=await scraper(),html=await readFile('render-tests/fixtures/shop.html','utf8'),products=m.parseProductHtml(html,'https://shop.example/',{container:'a.product-link',title:'h2.title',price:'.price',link:'a.product-link',image:'img'});assert.equal(products.length,2);assert.equal(products[0].url,'https://shop.example/p/perfume-1');assert.equal(products[0].image,'https://shop.example/images/one.jpg')});
test('invalid selectors are rejected before profile save',async()=>{const m=await scraper(),errors=m.validateSelectorConfig({container:'div[',title:'h2',price:'.price',link:'a',image:'img'});assert.ok(errors.container);assert.deepEqual(m.validateSelectorConfig({container:'div',title:'h2,.title',price:'.price',link:'a[href]',image:'img'}),{})});
test('all PHP pagination patterns build deterministic URLs',async()=>{const m=await scraper(),base={url:'https://shop.example/category/perfume?sort=new',paginationValue:'',pagination:'query_page'};assert.equal(m.pageUrl({...base,pagination:'query_page'},3),'https://shop.example/category/perfume?sort=new&page=3');assert.equal(m.pageUrl({...base,pagination:'query_custom',paginationValue:'paged'},2),'https://shop.example/category/perfume?sort=new&paged=2');assert.equal(m.pageUrl({...base,pagination:'path_pattern',paginationValue:'/page/{page}/'},4),'https://shop.example/category/perfume/page/4/?sort=new');assert.equal(m.pageUrl({...base,pagination:'full_pattern',paginationValue:'https://shop.example/list-{page}.html'},5),'https://shop.example/list-5.html')});
test('WooCommerce structured variations preserve groups, prices, stock, SKU and images',async()=>{const m=await scraper(),html=await readFile('render-tests/fixtures/variable.html','utf8'),data=m.parseVariations(cheerio.load(html),undefined,'https://shop.example/product/x');assert.equal(data.variations.length,2);assert.equal(data.variations[0].sku,'RED-L');assert.equal(data.variations[0].price,1250000);assert.equal(data.variations[1].stock,0);assert.equal(data.variations[0].image,'https://shop.example/images/red.jpg');assert.deepEqual(data.groups.find(x=>x.name==='color').options.sort(),['آبی','قرمز'].sort())});
