import { safeText } from './network.js';
import { escapeHtml, sha256 } from './utils.js';
import type { Product, Profile, Selectors } from './types.js';

declare class HTMLRewriter {
  on(selector:string,handlers:any):HTMLRewriter;
  transform(response:Response):Response;
}
const normalize=(value:string)=>value.replace(/[\u200c\u200d\u200e\u200f\ufeff]/g,' ').replace(/\s+/g,' ').trim();
const absolute=(value:string,base:string)=>{try{const url=new URL(value,base);return['http:','https:'].includes(url.protocol)?url.href:''}catch{return''}};
export function numberFromText(value:string):number{const en=value.replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))),groups=en.match(/\d[\d,٬.\s]*/g)||[];return groups.length?Math.max(...groups.map(item=>Number(item.replace(/\D/g,''))||0)):0;}
function selectorParts(selector:string):string[]{const out:string[]=[];let part='',round=0,square=0,quote='';for(const ch of selector){if(quote){part+=ch;if(ch===quote)quote='';continue}if(ch==='"'||ch==="'"){quote=ch;part+=ch}else if(ch==='('){round++;part+=ch}else if(ch===')'){round--;part+=ch}else if(ch==='['){square++;part+=ch}else if(ch===']'){square--;part+=ch}else if(ch===','&&!round&&!square){if(part.trim())out.push(part.trim());part=''}else part+=ch}if(part.trim())out.push(part.trim());return out;}
function scoped(container:string,field:string):string[]{return selectorParts(container).flatMap(a=>selectorParts(field).map(b=>`${a} ${b}`));}
function attr(element:any,names:string[]):string{for(const name of names){const value=element.getAttribute(name);if(value&&value!=='#')return value}return'';}
type Draft={title:string;priceText:string;url:string;image:string};
class CardHandler{active:Draft[]=[];products:Draft[];base:string;constructor(products:Draft[],base:string){this.products=products;this.base=base}element(element:any){const draft:Draft={title:normalize(element.getAttribute('title')||''),priceText:'',url:absolute(attr(element,['href','data-href','data-url','data-product-url']),this.base),image:absolute(attr(element,['data-src','data-lazy-src','data-original','src']),this.base)};this.active.push(draft);element.onEndTag(()=>{const index=this.active.lastIndexOf(draft);if(index>=0)this.active.splice(index,1);if(draft.title||draft.url)this.products.push(draft)})}current(){return this.active[this.active.length-1]}}
class TextFieldHandler{card:CardHandler;field:'title'|'priceText';captures:Array<{draft:Draft;text:string}>=[];constructor(card:CardHandler,field:'title'|'priceText'){this.card=card;this.field=field}element(element:any){const draft=this.card.current();if(!draft)return;const capture={draft,text:''};this.captures.push(capture);element.onEndTag(()=>{const i=this.captures.lastIndexOf(capture);if(i>=0)this.captures.splice(i,1);const value=normalize(capture.text);if(value&&!draft[this.field])draft[this.field]=value})}text(text:any){const capture=this.captures[this.captures.length-1];if(capture)capture.text+=text.text}}
class AttributeHandler{card:CardHandler;field:'url'|'image';base:string;names:string[];constructor(card:CardHandler,field:'url'|'image',base:string,names:string[]){this.card=card;this.field=field;this.base=base;this.names=names}element(element:any){const draft=this.card.current();if(!draft||draft[this.field])return;let value=attr(element,this.names);if(!value&&this.field==='image'){value=(element.getAttribute('srcset')||'').split(',')[0]?.trim().split(/\s+/)[0]||''}draft[this.field]=absolute(value,this.base)}}
class JsonLdHandler{chunks:string[]=[];active='';element(element:any){this.active='';element.onEndTag(()=>{if(this.active.trim())this.chunks.push(this.active);this.active=''})}text(text:any){this.active+=text.text}}
async function parseCards(html:string,base:string,selectors:Selectors):Promise<Product[]>{const drafts:Draft[]=[],card=new CardHandler(drafts,base),rewriter=new HTMLRewriter().on(selectors.container,card),title=new TextFieldHandler(card,'title'),price=new TextFieldHandler(card,'priceText'),link=new AttributeHandler(card,'url',base,['href','data-href','data-url','data-product-url']),image=new AttributeHandler(card,'image',base,['data-src','data-lazy-src','data-original','src']),jsonLd=new JsonLdHandler();for(const selector of scoped(selectors.container,selectors.title))rewriter.on(selector,title);for(const selector of scoped(selectors.container,selectors.price))rewriter.on(selector,price);for(const selector of scoped(selectors.container,selectors.link))rewriter.on(selector,link);for(const selector of scoped(selectors.container,selectors.image))rewriter.on(selector,image);rewriter.on('script[type="application/ld+json"]',jsonLd);await rewriter.transform(new Response(html)).text();
  if(!drafts.length)for(const block of jsonLd.chunks)try{const root=JSON.parse(block),items:any[]=[];const walk=(value:any)=>{if(!value||typeof value!=='object')return;if(String(value['@type']||'').toLowerCase().includes('product'))items.push(value);for(const child of Object.values(value))if(typeof child==='object')walk(child)};walk(root);for(const item of items){const offer=Array.isArray(item.offers)?item.offers[0]:item.offers||{},rawImage=Array.isArray(item.image)?item.image[0]:item.image||'';drafts.push({title:normalize(String(item.name||'')),priceText:String(offer.price||''),url:absolute(String(item.url||''),base),image:absolute(String(rawImage),base)})}}catch{}
  const products:Product[]=[];for(const draft of drafts){if(!draft.title&&!draft.url)continue;const key=(await sha256(draft.url||draft.title)).slice(0,32);products.push({sourceKey:key,title:draft.title.slice(0,300),price:numberFromText(draft.priceText),priceText:draft.priceText,url:draft.url,image:draft.image,images:draft.image?[draft.image]:[],sourcePage:base,scrapedAt:new Date().toISOString()})}return products;
}
class NextLinkHandler{url='';base:string;constructor(base:string){this.base=base}element(element:any){if(this.url)return;this.url=absolute(attr(element,['href','data-href','data-url']),this.base)}}
export async function scrapeListPage(url:string,selectors:Selectors,nextSelector=''):Promise<{products:Product[];nextUrl:string;url:string}>{const page=await safeText(url),next=new NextLinkHandler(page.url);if(nextSelector)await new HTMLRewriter().on(nextSelector,next).transform(new Response(page.text)).text();let products=await parseCards(page.text,page.url,selectors);if(!products.length){const fallbacks:Selectors[]=[{container:'li.product, article.product',title:'h2, h3, h4, .product-title, [class*="title"]',price:'.price, .amount, ins',link:'a[href]',image:'img'},{container:'.product-card, .product-item',title:'h2, h3, h4, .title',price:'.price, .amount',link:'a[href]',image:'img'}];for(const fallback of fallbacks){products=await parseCards(page.text,page.url,fallback);if(products.length)break}}return{products,nextUrl:next.url,url:page.url};}
export async function scrapeList(url:string,selectors:Selectors):Promise<Product[]>{return(await scrapeListPage(url,selectors)).products;}

class FirstText{value='';capture='';inside=false;element(element:any){if(this.value)return;this.capture='';this.inside=true;element.onEndTag(()=>{if(!this.value)this.value=normalize(this.capture);this.inside=false})}text(text:any){if(this.inside)this.capture+=text.text}}
class GalleryHandler{images:Set<string>;base:string;constructor(images:Set<string>,base:string){this.images=images;this.base=base}element(element:any){const image=absolute(attr(element,['data-src','data-large_image','data-lazy-src','data-original','href','src']),this.base);if(image)this.images.add(image)}}
async function firstText(html:string,selector?:string):Promise<string>{if(!selector)return'';const handler=new FirstText();await new HTMLRewriter().on(selector,handler).transform(new Response(html)).text();return handler.value;}
async function sanitizedFragment(html:string,selector:string,base:string):Promise<string>{const nonce=crypto.randomUUID(),start=`<!--s4-${nonce}-start-->`,end=`<!--s4-${nonce}-end-->`;let marked=false;const clean=(element:any)=>{for(const [name,value] of [...element.attributes] as Array<[string,string]>){const lower=name.toLowerCase();if(lower.startsWith('on')||['style','srcdoc','nonce','integrity'].includes(lower)){element.removeAttribute(name);continue}if(['href','src','poster'].includes(lower)){const resolved=absolute(value,base);resolved?element.setAttribute(name,resolved):element.removeAttribute(name)}}};const marker={element(element:any){clean(element);if(marked)return;marked=true;element.before(start,{html:true});element.after(end,{html:true})}},sanitize={element:clean},remove={element(element:any){element.remove()}};let rewriter=new HTMLRewriter().on(selector,marker);for(const s of scoped(selector,'*'))rewriter=rewriter.on(s,sanitize);for(const bad of ['script','style','iframe','object','embed','form','input','button','meta','link'])for(const s of scoped(selector,bad))rewriter=rewriter.on(s,remove);const output=await rewriter.transform(new Response(html)).text(),a=output.indexOf(start),b=output.indexOf(end,a+start.length);return a>=0&&b>a?output.slice(a+start.length,b):'';}
export async function scrapeDetails(product:Product,selectors:Selectors):Promise<Product>{if(!product.url)return product;const page=await safeText(product.url);product.shortDesc=await firstText(page.text,selectors.shortDesc)||product.shortDesc;product.sku=await firstText(page.text,selectors.sku)||product.sku;product.brand=await firstText(page.text,selectors.brand)||product.brand;product.category=await firstText(page.text,selectors.category)||product.category;const stock=await firstText(page.text,selectors.stock);if(stock)product.stock=numberFromText(stock);const weight=await firstText(page.text,selectors.weight);if(weight)product.weight=numberFromText(weight);if(selectors.longDesc)product.longDesc=await sanitizedFragment(page.text,selectors.longDesc,page.url)||product.longDesc;if(selectors.gallery){const images=new Set(product.images),handler=new GalleryHandler(images,page.url);await new HTMLRewriter().on(selectors.gallery,handler).transform(new Response(page.text)).text();product.images=[...images].slice(0,30);product.image ||= product.images[0]||''}return product;}
export function transformProduct(product:Product,profile:Profile):Product{product.title=normalize(product.title+profile.titleSuffix);const value=profile.priceValue;if(profile.priceMode==='add')product.price+=value;if(profile.priceMode==='percent')product.price*=1+value/100;if(profile.priceMode==='multiply')product.price*=value;if(profile.roundPrice>0)product.price=Math.ceil(product.price/profile.roundPrice)*profile.roundPrice;product.price=Math.round(product.price);return product;}
export function pageUrl(profile:Profile,page:number):string{const url=new URL(profile.url);if(page<=1||profile.pagination==='none')return url.href;if(profile.pagination==='path_page'){url.pathname=url.pathname.replace(/\/page\/\d+\/?$/i,'').replace(/\/$/,'')+`/page/${page}/`;return url.href}if(profile.pagination==='path_pattern'){const pattern=profile.paginationValue||'/page/{page}/';url.pathname=url.pathname.replace(/\/page\/\d+\/?$/i,'').replace(/\/$/,'')+pattern.replace('{page}',String(page));return url.href}if(profile.pagination==='full_pattern')return profile.paginationValue.replace('{page}',String(page));url.searchParams.set(profile.pagination==='query_custom'?(profile.paginationValue||'paged'):(profile.paginationValue||'page'),String(page));return url.href;}
export async function mapLimit<T>(items:T[],limit:number,fn:(item:T,index:number)=>Promise<void>):Promise<void>{let next=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(true){const index=next++;if(index>=items.length)return;await fn(items[index],index)}}));}
export async function testSelector(url:string,selector:string,type='text'):Promise<{count:number;values:string[]}>{const page=await safeText(url,4_000_000),values:string[]=[];let count=0;class Handler{capture='';element(element:any){count++;if(values.length>=20)return;if(type==='link'||type==='image'){const raw=type==='link'?attr(element,['href','data-href']):attr(element,['src','data-src','data-lazy-src','data-original']);const value=absolute(raw,page.url);if(value)values.push(value.slice(0,1000));return}this.capture='';element.onEndTag(()=>{const value=normalize(this.capture);if(value&&values.length<20)values.push(value.slice(0,1000));this.capture=''})}text(text:any){this.capture+=text.text}}await new HTMLRewriter().on(selector,new Handler()).transform(new Response(page.text)).text();return{count,values};}
export function safeLongDescription(value:string):string{return value||`<p>${escapeHtml(value)}</p>`;}
