import { getEnv, MIN_SECRET_LENGTH, validSecret } from './env.js';
import { safeText } from './network.js';
import { base64ToUtf8, bytesToBase64, safeEqual, textEncoder, utf8ToBase64 } from './utils.js';

declare class HTMLRewriter { on(selector:string,handlers:any):HTMLRewriter; transform(response:Response):Response; }
const secret=()=>{const env=getEnv(),value=env.VAULT_SECRET;if(!validSecret(value))throw new Error(`VAULT_SECRET must be at least ${MIN_SECRET_LENGTH} characters for visual selector tickets`);return value};
const base64url=(value:string)=>utf8ToBase64(value).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unbase64url=(value:string)=>base64ToUtf8(value.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(value.length/4)*4,'='));
async function sign(value:string):Promise<string>{const key=await crypto.subtle.importKey('raw',textEncoder.encode(secret()),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signature=new Uint8Array(await crypto.subtle.sign('HMAC',key,textEncoder.encode(value)));return bytesToBase64(signature).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
type Ticket={url:string;expires:number};
export async function createVisualTicket(url:string):Promise<string>{const encoded=base64url(JSON.stringify({url,expires:Date.now()+300_000}));return `${encoded}.${await sign(encoded)}`}
export async function readVisualTicket(ticket:string):Promise<Ticket>{const[encoded,signature]=ticket.split('.');if(!encoded||!signature||!safeEqual(signature,await sign(encoded)))throw new Error('Visual selector ticket is invalid');const payload=JSON.parse(unbase64url(encoded)) as Ticket;if(!payload.url||payload.expires<Date.now())throw new Error('Visual selector ticket has expired');return payload}
export async function renderVisualSelector(ticket:string):Promise<string>{const{url}=await readVisualTicket(ticket),page=await safeText(url,6_000_000);const sanitize={element(element:any){for(const[name,value]of[...element.attributes]as Array<[string,string]>){const lower=name.toLowerCase();if(lower.startsWith('on')||['srcdoc','nonce','integrity'].includes(lower)){element.removeAttribute(name);continue}if(['src','href','poster'].includes(lower)){if(element.tagName==='a'&&lower==='href'){element.setAttribute(name,'#');continue}try{const absolute=new URL(value,page.url);if(!['http:','https:','data:'].includes(absolute.protocol))element.removeAttribute(name);else element.setAttribute(name,absolute.href)}catch{element.removeAttribute(name)}}if(lower==='target'&&element.tagName==='a')element.removeAttribute(name)}const srcset=element.getAttribute('srcset');if(srcset){const value=srcset.split(',').map((part:string)=>{const[url,size='']=part.trim().split(/\s+/,2);try{return `${new URL(url,page.url).href} ${size}`.trim()}catch{return''}}).filter(Boolean).join(', ');value?element.setAttribute('srcset',value):element.removeAttribute('srcset')}}},remove={element(element:any){element.remove()}},head={element(element:any){element.prepend('<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">',{html:true});element.append(`<style>${PICKER_CSS}</style>`,{html:true})}},body={element(element:any){element.prepend(TOOLBAR,{html:true});element.append(`<script>${PICKER_JS}</script>`,{html:true})}};let rewriter=new HTMLRewriter().on('*',sanitize).on('script,iframe,object,embed,form,noscript,base,meta[http-equiv="refresh"],meta[http-equiv="Content-Security-Policy"]',remove).on('head',head).on('body',body);return rewriter.transform(new Response(page.text)).text()}

const TOOLBAR = `<div id="__s4bar"><select id="__s4mode"><option value="container">📦 کانتینر</option><option value="title">📝 عنوان</option><option value="price">💰 قیمت</option><option value="link">🔗 لینک</option><option value="image">🖼 تصویر فهرست</option><option value="shortDesc">توضیحات کوتاه</option><option value="longDesc">توضیحات بلند</option><option value="sku">SKU</option><option value="category">دسته‌بندی</option><option value="tags">برچسب‌ها</option><option value="weight">وزن</option><option value="stock">موجودی</option><option value="brand">برند</option><option value="detailImage">عکس اصلی محصول</option><option value="gallery">گالری</option><option value="variations">تنوع‌ها</option></select><button id="__s4up">⬆ والد</button><button id="__s4down">⬇ فرزند</button><code id="__s4selector">روی عنصر مورد نظر کلیک کنید</code><span id="__s4count">۰</span><button id="__s4save">✓ ثبت سلکتور</button></div>`;
const PICKER_CSS = `#__s4bar{position:fixed!important;z-index:2147483647!important;top:0!important;left:0!important;right:0!important;min-height:48px!important;background:#0f172af2!important;color:#fff!important;border-bottom:2px solid #a855f7!important;display:flex!important;align-items:center!important;gap:6px!important;padding:6px 9px!important;font:12px Tahoma,sans-serif!important;direction:rtl!important;box-shadow:0 4px 18px #0008!important}#__s4bar select,#__s4bar button{width:auto!important;min-width:0!important;background:#334155!important;color:#fff!important;border:1px solid #64748b!important;border-radius:6px!important;padding:7px 9px!important;font:11px Tahoma!important;cursor:pointer!important}#__s4bar #__s4save{background:#22c55e!important;color:#052e16!important;border-color:#22c55e!important;font-weight:bold!important}#__s4selector{flex:1!important;direction:ltr!important;text-align:left!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;background:#020617!important;color:#f0abfc!important;padding:7px!important;border-radius:5px!important}#__s4count{color:#67e8f9!important;white-space:nowrap!important}.__s4hover{outline:3px solid #a855f7!important;outline-offset:2px!important;cursor:crosshair!important}.__s4picked{outline:4px solid #22c55e!important;outline-offset:2px!important}body{padding-top:52px!important}@media(max-width:650px){#__s4bar{flex-wrap:wrap!important}#__s4selector{order:3;flex-basis:75%!important}body{padding-top:90px!important}}`;
const PICKER_JS = String.raw`(()=>{let current=null,hover=null;const bar=document.getElementById('__s4bar'),mode=document.getElementById('__s4mode'),label=document.getElementById('__s4selector'),count=document.getElementById('__s4count');const esc=v=>{try{return CSS.escape(v)}catch{return String(v).replace(/[^a-zA-Z0-9_-]/g,'\\$&')}};function selector(el){if(!el||el===document.body||el===document.documentElement)return el?.tagName?.toLowerCase()||'body';if(el.id){const s='#'+esc(el.id);if(document.querySelectorAll(s).length===1)return s}const parts=[];let node=el;while(node&&node!==document.body&&parts.length<5){let part=node.tagName.toLowerCase();const classes=[...node.classList].filter(x=>!x.startsWith('__s4')).slice(0,2);if(classes.length)part+='.'+classes.map(esc).join('.');let s=part;try{if(document.querySelectorAll(s).length===1){parts.unshift(part);break}}catch{}const siblings=node.parentElement?[...node.parentElement.children].filter(x=>x.tagName===node.tagName):[];if(siblings.length>1)part+=':nth-of-type('+(siblings.indexOf(node)+1)+')';parts.unshift(part);node=node.parentElement}return parts.join(' > ')}function choose(el){if(current)current.classList.remove('__s4picked');current=el;current.classList.add('__s4picked');const s=selector(current);label.textContent=s;try{count.textContent=document.querySelectorAll(s).length+' مورد'}catch{count.textContent='نامعتبر'}}document.addEventListener('mouseover',e=>{if(bar.contains(e.target))return;if(hover)hover.classList.remove('__s4hover');hover=e.target;hover.classList.add('__s4hover')},true);document.addEventListener('mouseout',e=>{if(e.target?.classList)e.target.classList.remove('__s4hover')},true);document.addEventListener('click',e=>{if(bar.contains(e.target))return;e.preventDefault();e.stopPropagation();choose(e.target)},true);document.getElementById('__s4up').onclick=()=>{if(current?.parentElement&&!bar.contains(current.parentElement))choose(current.parentElement)};document.getElementById('__s4down').onclick=()=>{if(current?.firstElementChild)choose(current.firstElementChild)};document.getElementById('__s4save').onclick=()=>{if(!current)return;const s=selector(current),preview=(current.innerText||current.getAttribute('src')||current.getAttribute('href')||'').trim().replace(/\s+/g,' ').slice(0,250);parent.postMessage({type:'scraper4-selector',mode:mode.value,selector:s,preview,count:document.querySelectorAll(s).length},location.origin)};window.addEventListener('message',e=>{if(e.origin!==location.origin)return;if(e.data?.type==='scraper4-mode'&&e.data.mode)mode.value=e.data.mode})})();`;

